# Generated by Django 5.2.3 on 2025-06-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_produto_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="password",
            field=models.CharField(
                default="", help_text="Senha (hash)", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="endereco",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
