# Generated by Django 5.2.3 on 2025-06-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_itemcarrinho_preco"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(default="12345678912", max_length=11),
        ),
    ]
