# Generated by Django 5.2.3 on 2025-06-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_cliente_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="bairro",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cep",
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cidade",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="cliente",
            name="complemento",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="cliente",
            name="estado",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="cliente",
            name="numero",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
